# Generated by Django 4.2.7 on 2026-01-03 11:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('csi300', '0022_add_generation_task_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template identifier (e.g., 'investment_summary_v1')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Human-readable template name (e.g., 'Investment Summary Report')", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Template description and usage notes')),
                ('latex_content', models.TextField(help_text='Main LaTeX template content using Jinja2 syntax for variable substitution')),
                ('preamble', models.TextField(blank=True, default='', help_text='LaTeX preamble (package imports, custom commands)')),
                ('page_size', models.CharField(default='a4paper', help_text='LaTeX page size (a4paper, letterpaper, etc.)', max_length=20)),
                ('margins', models.JSONField(blank=True, default=dict, help_text='Page margins as JSON (e.g., {"top": "2cm", "bottom": "2cm", "left": "2.5cm", "right": "2.5cm"})')),
                ('header_left', models.CharField(blank=True, default='', help_text='Left header content', max_length=200)),
                ('header_right', models.CharField(blank=True, default='', help_text='Right header content', max_length=200)),
                ('footer_center', models.CharField(blank=True, default='', help_text='Center footer content (e.g., page numbers)', max_length=200)),
                ('charts_config', models.JSONField(blank=True, default=list, help_text='Chart definitions as JSON array')),
                ('version', models.CharField(default='1.0', help_text='Template version', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for use')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template for new reports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF Template',
                'verbose_name_plural': 'PDF Templates',
                'db_table': 'pdf_template',
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PDFTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique task identifier', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('generating_charts', 'Generating Charts'), ('compiling', 'Compiling LaTeX'), ('uploading', 'Uploading to S3'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current task status', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if task failed')),
                ('s3_key', models.CharField(blank=True, default='', help_text='S3 object key for the generated PDF', max_length=500)),
                ('download_url', models.URLField(blank=True, default='', help_text='Pre-signed S3 download URL', max_length=2000)),
                ('download_url_expires_at', models.DateTimeField(blank=True, help_text='Expiration time for the download URL', null=True)),
                ('requested_by', models.CharField(blank=True, default='', help_text='User ID or IP address of requester', max_length=100)),
                ('request_metadata', models.JSONField(blank=True, default=dict, help_text='Additional request metadata (user agent, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When task completed (success or failure)', null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Total processing time in milliseconds', null=True)),
                ('company', models.ForeignKey(help_text='Company for which PDF is being generated', on_delete=django.db.models.deletion.CASCADE, related_name='pdf_tasks', to='csi300.csi300company')),
                ('template', models.ForeignKey(help_text='Template used for this PDF generation', on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='pdf_service.pdftemplate')),
            ],
            options={
                'verbose_name': 'PDF Task',
                'verbose_name_plural': 'PDF Tasks',
                'db_table': 'pdf_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='pdf_task_status_39fd91_idx'), models.Index(fields=['company', '-created_at'], name='pdf_task_company_3f4daa_idx')],
            },
        ),
    ]
