# Generated manually for PDF Service default template
"""
Create the default Investment Summary PDF template.

This migration inserts the initial PDFTemplate record that the system
needs to generate investment summary reports.
"""

from django.db import migrations

# Template content from latex-service/templates/investment_summary.tex.j2
DEFAULT_TEMPLATE_CONTENT = r'''%# Title Page
\begin{titlepage}
    \centering
    \vspace*{2cm}

    {\Huge\bfseries\color{primary} Investment Summary Report}

    \vspace{1cm}

    {\LARGE \VAR{ summary.company_name | escape }}

    \vspace{0.5cm}

    {\large \textcolor{textgray}{(\VAR{ company.ticker | escape })}}

    \vspace{2cm}

    \begin{tabular}{ll}
        \textbf{Exchange:} & \VAR{ company.exchange_code | escape } \\
        \textbf{Sector:} & \VAR{ company.sector | escape } \\
        \textbf{Report Date:} & \VAR{ report_date } \\
    \end{tabular}

    \vfill

    {\footnotesize Generated by ALFIE Investment Analysis System}

\end{titlepage}

%# Table of Contents
\tableofcontents
\newpage

%# Executive Summary
\section{Executive Summary}

\subsection{Investment Recommendation}

\begin{center}
\BLOCK{ if summary.recommended_action == 'BUY' }
    {\Huge\bfseries\color{secondary} ★ BUY ★}
\BLOCK{ elif summary.recommended_action == 'SELL' }
    {\Huge\bfseries\color{danger} ✕ SELL ✕}
\BLOCK{ elif summary.recommended_action == 'HOLD' }
    {\Huge\bfseries\color{accent} ◆ HOLD ◆}
\BLOCK{ else }
    {\Huge\bfseries\color{textgray} ? NEUTRAL ?}
\BLOCK{ endif }
\end{center}

\vspace{0.5cm}

\VAR{ summary.recommended_action_detail | escape_para }

\subsection{Key Highlights}

\begin{itemize}[leftmargin=*]
\BLOCK{ if company.price_date }
    \item \textbf{Stock Price:} \VAR{ company.previous_close | currency('USD') } (as of \VAR{ company.price_date | date })
\BLOCK{ else }
    \item \textbf{Stock Price:} \VAR{ company.previous_close | currency('USD') }
\BLOCK{ endif }
    \item \textbf{Market Cap:} \VAR{ summary.market_cap_display | escape }
\BLOCK{ if company.price_52w_low and company.price_52w_high }
    \item \textbf{52-Week Range:} \VAR{ company.price_52w_low | currency('USD') } — \VAR{ company.price_52w_high | currency('USD') }
\BLOCK{ else }
    \item \textbf{52-Week Range:} N/A
\BLOCK{ endif }
    \item \textbf{P/E Ratio:} \VAR{ company.pe_ratio_trailing | number }
    \item \textbf{EPS (TTM):} \VAR{ company.eps_trailing | currency('USD') }
    \item \textbf{Dividend Yield:} \VAR{ company.dividend_yield_fy0 | percentage }
\end{itemize}

%# Company Overview
\section{Company Overview}

\subsection{Business Description}

\VAR{ summary.business_overview | escape_para }

\subsection{Industry Position}

\begin{tabular}{ll}
    \textbf{Sector:} & \VAR{ company.sector | escape } \\
    \textbf{Industry:} & \VAR{ company.industry | escape } \\
    \textbf{Exchange:} & \VAR{ company.exchange_code | escape } \\
    \textbf{Country:} & \VAR{ company.country | escape } \\
\end{tabular}

%# Financial Analysis
\section{Financial Analysis}

\subsection{Valuation Metrics}

\begin{longtable}{lrr}
    \toprule
    \textbf{Metric} & \textbf{Value} & \textbf{Industry Avg} \\
    \midrule
    \endhead

    P/E Ratio (Trailing) & \VAR{ company.pe_ratio_trailing | number } & — \\
\BLOCK{ if company.pe_ratio_forward }
    P/E Ratio (Forward) & \VAR{ company.pe_ratio_forward | number } & — \\
\BLOCK{ else }
    P/E Ratio (Forward) & N/A & — \\
\BLOCK{ endif }
\BLOCK{ if company.pb_ratio }
    P/B Ratio & \VAR{ company.pb_ratio | number } & — \\
\BLOCK{ else }
    P/B Ratio & N/A & — \\
\BLOCK{ endif }
\BLOCK{ if company.ps_ratio }
    P/S Ratio & \VAR{ company.ps_ratio | number } & — \\
\BLOCK{ else }
    P/S Ratio & N/A & — \\
\BLOCK{ endif }
\BLOCK{ if company.ev_ebitda }
    EV/EBITDA & \VAR{ company.ev_ebitda | number } & — \\
\BLOCK{ else }
    EV/EBITDA & N/A & — \\
\BLOCK{ endif }

    \bottomrule
\end{longtable}

\subsection{Profitability Metrics}

\begin{longtable}{lr}
    \toprule
    \textbf{Metric} & \textbf{Value} \\
    \midrule
    \endhead

    Return on Equity (ROE) & \VAR{ company.roe_trailing | percentage } \\
    Return on Assets (ROA) & \VAR{ company.roa_trailing | percentage } \\
\BLOCK{ if company.gross_margin }
    Gross Margin & \VAR{ company.gross_margin | percentage } \\
\BLOCK{ else }
    Gross Margin & N/A \\
\BLOCK{ endif }
    Operating Margin & \VAR{ company.operating_margin | percentage } \\
\BLOCK{ if company.net_margin }
    Net Margin & \VAR{ company.net_margin | percentage } \\
\BLOCK{ else }
    Net Margin & N/A \\
\BLOCK{ endif }

    \bottomrule
\end{longtable}

\subsection{Business Performance}

\VAR{ summary.business_performance | escape_para }

\subsection{Financial Stability}

\VAR{ summary.financial_stability | escape_para }

\begin{longtable}{lr}
    \toprule
    \textbf{Metric} & \textbf{Value} \\
    \midrule
    \endhead

    Current Ratio & \VAR{ company.current_ratio | number } \\
    Quick Ratio & \VAR{ company.quick_ratio | number } \\
    Debt to Equity & \VAR{ company.debt_to_equity | number } \\
    Interest Coverage & \VAR{ company.interest_coverage | number } \\

    \bottomrule
\end{longtable}

%# Charts
\section{Visual Analysis}

\BLOCK{ if 'stock_price' in charts }
\subsection{Stock Price Performance}

\begin{figure}[H]
    \centering
    \includegraphics[width=0.9\textwidth]{\VAR{ charts['stock_price'] }}
    \caption{52-Week Stock Price Performance}
\end{figure}
\BLOCK{ endif }

\BLOCK{ if 'roe_trend' in charts }
\subsection{Return on Equity Trend}

\begin{figure}[H]
    \centering
    \includegraphics[width=0.85\textwidth]{\VAR{ charts['roe_trend'] }}
    \caption{Historical ROE Performance}
\end{figure}
\BLOCK{ endif }

\BLOCK{ if 'pe_ratio' in charts }
\subsection{P/E Ratio Trend}

\begin{figure}[H]
    \centering
    \includegraphics[width=0.85\textwidth]{\VAR{ charts['pe_ratio'] }}
    \caption{Historical P/E Ratio vs Industry Average}
\end{figure}
\BLOCK{ endif }

%# Risk Assessment
\section{Risk Assessment}

\subsection{Identified Risks}

\VAR{ summary.risks_anomalies | escape_para }

\subsection{Risk Factors}

\begin{itemize}[leftmargin=*]
\BLOCK{ if summary.risk_factors }
\BLOCK{ for risk in summary.risk_factors }
    \item \VAR{ risk | escape }
\BLOCK{ endfor }
\BLOCK{ else }
    \item Market volatility and economic conditions
    \item Industry-specific regulatory changes
    \item Competitive pressures
    \item Currency and interest rate fluctuations
\BLOCK{ endif }
\end{itemize}

%# Growth Outlook
\section{Growth Outlook}

\subsection{Analyst Projections}

\begin{longtable}{lr}
    \toprule
    \textbf{Metric} & \textbf{Estimate} \\
    \midrule
    \endhead

    EPS Growth (YoY) & \VAR{ company.eps_growth_percent | percentage } \\
\BLOCK{ if company.revenue_growth_percent }
    Revenue Growth & \VAR{ company.revenue_growth_percent | percentage } \\
\BLOCK{ else }
    Revenue Growth & N/A \\
\BLOCK{ endif }
\BLOCK{ if company.target_price_mean }
    Target Price (Mean) & \VAR{ company.target_price_mean | currency('USD') } \\
\BLOCK{ else }
    Target Price (Mean) & N/A \\
\BLOCK{ endif }

    \bottomrule
\end{longtable}

\subsection{Growth Analysis}

\VAR{ summary.growth_analysis | escape_para }

%# Appendix
\appendix
\section{Data Sources}

This report was generated using data from the following sources:

\begin{itemize}
    \item Market data: Refinitiv, Yahoo Finance
    \item Financial statements: Company filings, SEC EDGAR
    \item Analyst estimates: Refinitiv consensus
    \item Report generation: ALFIE Investment Analysis System
\end{itemize}

\section{Disclaimer}

\textcolor{textgray}{\small
This report is for informational purposes only and does not constitute investment advice.
Past performance is not indicative of future results.
Always conduct your own research and consult with a qualified financial advisor before making investment decisions.
}

\vfill

\begin{center}
{\footnotesize Report generated on \VAR{ report_date } by ALFIE}
\end{center}
'''

DEFAULT_PREAMBLE = r'''% Document class and packages
\documentclass[11pt,a4paper]{article}

% Page geometry
\usepackage[top=2.5cm, bottom=2.5cm, left=2.5cm, right=2.5cm]{geometry}

% Fonts - use XeLaTeX defaults (Latin Modern)
% No fontspec configuration needed for English-only reports

% Colors
\usepackage{xcolor}
\definecolor{primary}{HTML}{1a365d}
\definecolor{secondary}{HTML}{2f855a}
\definecolor{accent}{HTML}{dd6b20}
\definecolor{danger}{HTML}{c53030}
\definecolor{textgray}{HTML}{4a5568}

% Tables
\usepackage{booktabs}
\usepackage{longtable}

% Graphics
\usepackage{graphicx}
\usepackage{float}

% Lists
\usepackage{enumitem}

% Hyperlinks
\usepackage{hyperref}
\hypersetup{
    colorlinks=true,
    linkcolor=primary,
    urlcolor=primary
}

% Headers and footers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{\small Investment Summary Report}
\fancyhead[R]{\small \VAR{ company.ticker | escape }}
\fancyfoot[C]{\small Page \thepage}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}

% Document begins
\begin{document}
'''


def create_default_template(apps, schema_editor):
    """Create the default investment summary template."""
    PDFTemplate = apps.get_model('pdf_service', 'PDFTemplate')

    # Check if template already exists
    if not PDFTemplate.objects.filter(name='investment_summary_v1').exists():
        PDFTemplate.objects.create(
            name='investment_summary_v1',
            display_name='Investment Summary Report',
            description='Standard investment summary report template for CSI300 companies. '
                       'Includes executive summary, financial analysis, charts, risk assessment, '
                       'and growth outlook sections.',
            latex_content=DEFAULT_TEMPLATE_CONTENT,
            preamble=DEFAULT_PREAMBLE,
            page_size='a4paper',
            margins={
                'top': '2.5cm',
                'bottom': '2.5cm',
                'left': '2.5cm',
                'right': '2.5cm'
            },
            header_left='Investment Summary Report',
            header_right='{{ company.ticker }}',
            footer_center='Page {{ page }}',
            # IMPORTANT: 'type' must match registered chart generators in
            # latex-service/chart_generator.py (e.g., 'stock_price', NOT 'line')
            charts_config=[
                {'name': 'stock_price', 'type': 'stock_price', 'title': 'Stock Price Performance'},
                {'name': 'roe_trend', 'type': 'roe_trend', 'title': 'ROE Trend'},
                {'name': 'pe_ratio', 'type': 'pe_ratio', 'title': 'P/E Ratio Trend'},
                {'name': 'financial_summary', 'type': 'financial_summary', 'title': 'Financial Summary'},
            ],
            version='1.0',
            is_active=True,
            is_default=True,
        )


def remove_default_template(apps, schema_editor):
    """Remove the default template (reverse migration)."""
    PDFTemplate = apps.get_model('pdf_service', 'PDFTemplate')
    PDFTemplate.objects.filter(name='investment_summary_v1').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_service', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_template, remove_default_template),
    ]

