# ==========================================
# PROMPT_TEMPLATE - 主模板
# 由段落常量拼装生成
# ==========================================

from .sections import (
    SECTION_BUSINESS_OVERVIEW,
    SECTION_HEADER,
    SECTION_PERFORMANCE_FINANCIALS,
    SECTION_RECOMMENDATION_TAKEAWAYS,
    SECTION_RISKS_ANALYSTS,
    SECTION_SOURCES,
    SECTION_TRENDS_COMPETITION,
)

PROMPT_TEMPLATE = (
    SECTION_HEADER
    + SECTION_BUSINESS_OVERVIEW
    + SECTION_PERFORMANCE_FINANCIALS
    + SECTION_TRENDS_COMPETITION
    + SECTION_RISKS_ANALYSTS
    + SECTION_RECOMMENDATION_TAKEAWAYS
    + SECTION_SOURCES
)


__all__ = ["PROMPT_TEMPLATE"]

