# Generated by Django for BEA app
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeaIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=50)),
                ('indicator_name', models.CharField(max_length=200)),
                ('indicator_type', models.CharField(max_length=50)),
                ('table_name', models.CharField(blank=True, max_length=50, null=True)),
                ('line_number', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField()),
                ('time_period', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('source', models.CharField(default='BEA', max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('dataset_name', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bea_indicators',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='beaindicator',
            unique_together={('series_id', 'time_period')},
        ),
    ]