# Generated by Django 5.2.4 on 2025-09-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeaIndicatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('table_name', models.CharField(max_length=50)),
                ('line_description', models.CharField(max_length=500)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(default='Q', max_length=20)),
                ('years', models.CharField(default='2022,2023,2024,2025', max_length=100)),
                ('category', models.CharField(default='consumer_spending', max_length=100)),
                ('fallback_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('api_endpoint', models.CharField(max_length=100, unique=True)),
                ('priority', models.IntegerField(default=999)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_fetch', models.BooleanField(default=True)),
                ('dataset_name', models.CharField(default='NIPA', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('additional_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'bea_indicator_configs',
                'ordering': ['priority', 'series_id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BeaSeriesInfo',
            fields=[
                ('series_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('table_name', models.CharField(blank=True, max_length=50, null=True)),
                ('line_number', models.CharField(blank=True, max_length=10, null=True)),
                ('line_description', models.CharField(blank=True, max_length=200, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('dataset_name', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bea_series_info',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='beaindicator',
            options={'managed': True, 'ordering': ['-date']},
        ),
    ]
