# Generated by Django 4.2.7 on 2026-01-17 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('daily_briefing', 'Daily Briefing'), ('forensic_accounting', 'Forensic Accounting')], max_length=50)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping Data'), ('waiting_stage2', 'Waiting for Stage 2'), ('generating', 'Generating Report'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stage1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('stage2_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result_urls', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyBriefingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date when the data was scraped')),
                ('source_type', models.CharField(choices=[('page_one', 'Page One'), ('stock_market', 'Stock Market Update'), ('bond_market', 'Bond Market Update')], help_text='Type of source: page_one, stock_market, or bond_market', max_length=20)),
                ('source_url', models.URLField(help_text='URL of the scraped page')),
                ('content', models.TextField(help_text='Scraped content from Briefing.com')),
                ('content_length', models.IntegerField(help_text='Character count of the content')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the content was scraped')),
            ],
            options={
                'verbose_name': 'Daily Briefing Data',
                'verbose_name_plural': 'Daily Briefing Data',
                'ordering': ['-date', 'source_type'],
                'unique_together': {('date', 'source_type')},
            },
        ),
        migrations.CreateModel(
            name='DailyBriefingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of the report')),
                ('report_type', models.CharField(choices=[('long_version', 'Long Version'), ('quick_version', 'Quick Version')], help_text='Type of report: long_version or quick_version', max_length=20)),
                ('content', models.TextField(help_text='Report content in Markdown format')),
                ('drive_url', models.URLField(blank=True, default='', help_text='Google Drive URL for the uploaded document')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the report was created')),
                ('task', models.ForeignKey(help_text='The automation task that generated this report', on_delete=django.db.models.deletion.CASCADE, related_name='briefing_reports', to='automation.automationtask')),
            ],
            options={
                'verbose_name': 'Daily Briefing Report',
                'verbose_name_plural': 'Daily Briefing Reports',
                'ordering': ['-date', 'report_type'],
                'unique_together': {('date', 'report_type')},
            },
        ),
    ]
