/**
 * MEM Dashboard API Configuration - Production
 * Auto-generated by deployment script
 * Generated at: 2025-11-15 21:18:44
 */

// Production API configuration
const API_CONFIGS = {
    DJANGO: {
        name: 'Django REST API',
        baseUrl: 'https://mem-dashboard-alb-1995066194.ap-east-1.elb.amazonaws.com/api',
        description: 'Django REST Framework API with PostgreSQL data',
        version: '2.0',
        status: 'production'
    }
};

// Get current API configuration
const getCurrentApiConfig = () => {
    return API_CONFIGS.DJANGO;
};

// Export configuration
window.API_CONFIG = getCurrentApiConfig();
window.API_CONFIGS = API_CONFIGS;

// Initialize production configuration
console.log('🚀 MEM Dashboard API Configuration - Production');
console.log(`📊 API Name: ${window.API_CONFIG.name}`);
console.log(`🔗 API URL: ${window.API_CONFIG.baseUrl}`);
console.log(`📝 Description: ${window.API_CONFIG.description}`);
console.log('✅ Production mode enabled');

// Production fetch interceptor
window.originalFetch = window.fetch;
window.fetch = (url, options) => {
    console.log('🔍 [PROD] Fetch called with URL:', url);
    
    // Handle relative API calls
    if (url.startsWith('/api/')) {
        url = window.API_CONFIG.baseUrl + url.replace('/api', '');
        console.log('🔄 [PROD] Redirected to:', url);
    }
    
    return window.originalFetch(url, options);
};

console.log('✅ Production API interceptor configured');
