# Generated by Django 4.2.7 on 2025-07-24 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Content Category',
                'verbose_name_plural': 'Content Categories',
                'db_table': 'content_contentcategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modal_id', models.CharField(help_text='Modal ID used by frontend, e.g.: motor-vehicles', max_length=100, unique=True, verbose_name='Modal ID')),
                ('title', models.CharField(help_text='Title displayed in the modal', max_length=200, verbose_name='Title')),
                ('content_type', models.CharField(choices=[('consumer-spending', 'Consumer Spending'), ('motor-vehicles', 'Motor Vehicles'), ('services-exports', 'Services Exports'), ('goods-exports', 'Goods Exports'), ('economic-indicators', 'Economic Indicators'), ('investment-components', 'Investment Components'), ('market-analysis', 'Market Analysis')], help_text='Specific type of content', max_length=50, verbose_name='Content Type')),
                ('description', models.TextField(help_text='Detailed description displayed in the modal', verbose_name='Description')),
                ('importance', models.TextField(help_text='Explanation of why this indicator/content is important', verbose_name='Importance')),
                ('source', models.CharField(help_text='Source of the data', max_length=500, verbose_name='Data Source')),
                ('breakdown_data', models.JSONField(blank=True, help_text='Structured breakdown data in JSON format', null=True, verbose_name='Breakdown Data')),
                ('additional_info', models.JSONField(blank=True, help_text='Additional information in JSON format', null=True, verbose_name='Additional Information')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display in frontend', verbose_name='Is Active')),
                ('priority', models.IntegerField(default=100, help_text='Lower number = higher priority', verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, help_text='Category this content belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.contentcategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contents', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contents', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Modal Content',
                'verbose_name_plural': 'Modal Contents',
                'db_table': 'content_modalcontent',
                'ordering': ['priority', 'title'],
                'indexes': [models.Index(fields=['modal_id'], name='content_mod_modal_i_6b0af6_idx'), models.Index(fields=['content_type'], name='content_mod_content_e73441_idx'), models.Index(fields=['is_active'], name='content_mod_is_acti_02cd73_idx')],
            },
        ),
    ]
