# Generated by Django 5.2.4 on 2025-08-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FredUsSeriesInfo',
            fields=[
                ('series_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('seasonal_adjustment', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'US FRED Series Info',
                'verbose_name_plural': 'US FRED Series Info',
                'db_table': 'fred_us_series_info',
            },
        ),
        migrations.CreateModel(
            name='FredUsIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(db_index=True, max_length=50)),
                ('indicator_name', models.CharField(max_length=200)),
                ('indicator_type', models.CharField(max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('source', models.CharField(default='FRED', max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'US FRED Indicator',
                'verbose_name_plural': 'US FRED Indicators',
                'db_table': 'fred_us_indicators',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['series_id', '-date'], name='idx_us_series_date'), models.Index(fields=['indicator_type', '-date'], name='idx_us_type_date'), models.Index(fields=['series_id', '-updated_at'], name='idx_us_series_updated')],
                'unique_together': {('series_id', 'date')},
            },
        ),
    ]
