# Generated by Django 4.2.7 on 2025-08-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fred_us', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FredUsIndicatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(help_text='FRED系列ID', max_length=50, unique=True)),
                ('name', models.CharField(help_text='指标名称', max_length=200)),
                ('description', models.TextField(blank=True, help_text='详细描述')),
                ('indicator_type', models.CharField(help_text='指标类型分类', max_length=50)),
                ('units', models.CharField(blank=True, help_text='数据单位', max_length=100)),
                ('frequency', models.CharField(default='Monthly', help_text='数据频率', max_length=20)),
                ('category', models.CharField(default='economic', help_text='指标分类', max_length=100)),
                ('api_endpoint', models.CharField(help_text='API端点路径', max_length=100, unique=True)),
                ('fallback_value', models.DecimalField(blank=True, decimal_places=4, help_text='备用数值', max_digits=15, null=True)),
                ('priority', models.IntegerField(default=999, help_text='处理优先级')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('auto_fetch', models.BooleanField(default=True, help_text='是否自动抓取')),
                ('fetch_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='自动抓取频率', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('additional_config', models.JSONField(blank=True, default=dict, help_text='额外JSON配置')),
                ('last_fetch_time', models.DateTimeField(blank=True, help_text='最后抓取时间', null=True)),
                ('fetch_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='pending', help_text='抓取状态', max_length=20)),
            ],
            options={
                'verbose_name': 'US FRED Indicator Configuration',
                'verbose_name_plural': 'US FRED Indicator Configurations',
                'db_table': 'fred_us_indicator_configs',
                'ordering': ['priority', 'series_id'],
                'managed': True,
            },
        ),
    ]
