# Generated by Django 4.2.7 on 2025-08-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fred_us', '0003_increase_field_lengths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fredusindicator',
            name='frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
