# Generated by Django 5.2.4 on 2025-09-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSI300Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='行业')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='板块')),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='市值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CSI300公司',
                'verbose_name_plural': 'CSI300公司列表',
                'db_table': 'csi300_companies',
                'ordering': ['code'],
            },
        ),
    ]
