# Generated by Django to match local database structure
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0001_initial'),
    ]

    operations = [
        # Drop the old table if exists
        migrations.RunSQL("DROP TABLE IF EXISTS csi300_investment_summary CASCADE;", 
                         reverse_sql="-- No reverse SQL needed"),
        
        # Recreate the table with correct structure matching local database
        migrations.RunSQL("""
            CREATE TABLE csi300_investment_summary (
                id bigserial NOT NULL,
                report_date date NOT NULL,
                stock_price_previous_close numeric(10,6) NOT NULL,
                market_cap_display varchar(100) NOT NULL,
                recommended_action varchar(50) NOT NULL,
                business_overview text NOT NULL,
                business_performance text NOT NULL,
                industry_context text NOT NULL,
                financial_stability text NOT NULL,
                key_financials_valuation text NOT NULL,
                big_trends_events text NOT NULL,
                customer_segments text NOT NULL,
                competitive_landscape text NOT NULL,
                risks_anomalies text NOT NULL,
                forecast_outlook text NOT NULL,
                investment_firms_views text NOT NULL,
                industry_ratio_analysis text NOT NULL,
                tariffs_supply_chain_risks text NOT NULL,
                key_takeaways text NOT NULL,
                sources text NOT NULL,
                created_at timestamptz NOT NULL DEFAULT NOW(),
                updated_at timestamptz NOT NULL DEFAULT NOW(),
                company_id bigint NOT NULL,
                recommended_action_detail text NOT NULL,
                CONSTRAINT csi300_investment_summary_pkey PRIMARY KEY (id),
                CONSTRAINT csi300_investment_summary_company_id_key UNIQUE (company_id),
                CONSTRAINT csi300_investment_su_company_id_33cbcc2b_fk_csi300_co 
                    FOREIGN KEY (company_id) REFERENCES csi300_company(id) 
                    DEFERRABLE INITIALLY DEFERRED
            );
            
            CREATE INDEX IF NOT EXISTS csi300_investment_summary_company_id_idx 
            ON csi300_investment_summary(company_id);
        """, 
        reverse_sql="DROP TABLE IF EXISTS csi300_investment_summary CASCADE;"),
    ]