# Generated by Django to fix currency field length
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0002_fix_investment_summary_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csi300company',
            name='currency',
            field=models.CharField(blank=True, help_text='Currency', max_length=20, null=True),
        ),
    ]