# Generated by Django 5.2.4 on 2025-09-26 03:30

from django.db import migrations
from django.db import models


def populate_null_big_trends_events(apps, schema_editor):
    """为空的big_trends_events字段提供默认值"""
    CSI300InvestmentSummary = apps.get_model('csi300', 'CSI300InvestmentSummary')
    CSI300InvestmentSummary.objects.filter(big_trends_events__isnull=True).update(
        big_trends_events='Information not available in source document'
    )


def reverse_populate_null_big_trends_events(apps, schema_editor):
    """反向操作：将默认值设为空"""
    CSI300InvestmentSummary = apps.get_model('csi300', 'CSI300InvestmentSummary')
    CSI300InvestmentSummary.objects.filter(
        big_trends_events='Information not available in source document'
    ).update(big_trends_events=None)


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0003_fix_currency_field_length'),
    ]

    operations = [
        # 首先为空值提供默认值
        migrations.RunPython(
            populate_null_big_trends_events,
            reverse_populate_null_big_trends_events,
        ),
        # 然后将字段设为非空
        migrations.AlterField(
            model_name='csi300investmentsummary',
            name='big_trends_events',
            field=models.TextField(help_text='Big trends and events'),
        ),
    ]
