# Generated by Django 5.2.4 on 2025-09-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0007_final_unique_together_fix'),
    ]

    operations = [
        # Replace the problematic AlterUniqueTogether operation with a no-op
        # The unique_together constraint was already handled in the table structure
        migrations.RunSQL(
            sql="SELECT 1; -- No-op migration to avoid unique_together constraint error",
            reverse_sql="SELECT 1; -- No reverse operation needed",
        ),
    ]
