# Generated by Django 5.2.4 on 2025-09-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0008_alter_csi300investmentsummary_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='csi300investmentsummary',
            unique_together=set(),
        ),
    ]
