# Generated by Django 5.2.4 on 2025-09-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0008_alter_csi300investmentsummary_unique_together'),
    ]

    operations = [
        # Skip this operation - no constraint exists to remove
        # The unique_together was already handled in previous migrations
        migrations.RunSQL(
            sql="SELECT 1; -- No-op: unique_together constraint doesn't exist",
            reverse_sql="SELECT 1; -- No reverse operation needed",
        ),
    ]
