# Generated by Django 5.2.4 on 2025-10-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0009_alter_csi300investmentsummary_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='csi300company',
            name='im_sector',
            field=models.CharField(blank=True, help_text='IM Sector (code + industry)', max_length=150, null=True),
        ),
    ]
