# Generated by Django 5.2.4 on 2025-10-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0010_add_im_sector'),
    ]

    operations = [
    ]
