# Generated by Django 5.2.4 on 2025-10-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0011_migrate_im_sector_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csi300company',
            name='im_code',
        ),
        migrations.RemoveField(
            model_name='csi300company',
            name='industry',
        ),
    ]
