# Generated by Django 5.2.4 on 2025-10-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0012_remove_old_im_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csi300company',
            name='im_sector',
            field=models.CharField(blank=True, help_text='IM Sector (combined IM Code and Industry)', max_length=150, null=True),
        ),
    ]
