# Generated by Django 5.2.4 on 2025-10-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0014_rename_sub_industry_to_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csi300company',
            name='im_sector',
            field=models.CharField(blank=True, help_text='IM Sector (combined from im_code and industry)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='csi300company',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry', max_length=100, null=True),
        ),
    ]
