# Generated by Django 5.2.4 on 2025-10-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0015_alter_csi300company_im_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csi300company',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='csi300investmentsummary',
            name='market_cap_display',
            field=models.CharField(default='', help_text='Market cap display format', max_length=200),
        ),
    ]
