# Generated by Django 5.2.4 on 2025-10-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0016_alter_industry_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csi300company',
            name='interest_coverage_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Interest coverage ratio', max_digits=15, null=True),
        ),
    ]
