# Generated by Django 5.2.4 on 2025-10-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0017_alter_csi300company_interest_coverage_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='csi300company',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Previous close price', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='csi300company',
            name='price_local_currency',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Price in local currency (Open)', max_digits=20, null=True),
        ),
    ]
