# Generated by Django 5.2.4 on 2025-11-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0019_csi300hsharescompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='csi300company',
            name='region',
            field=models.CharField(blank=True, help_text='Region (e.g., Mainland China, Hong Kong)', max_length=50, null=True),
        ),
    ]
