# Generated by Django 4.2.7 on 2025-12-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csi300', '0021_fix_currency_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, help_text='UUID task identifier', max_length=36, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current task status', max_length=20)),
                ('progress_message', models.CharField(blank=True, default='', help_text='Current progress message', max_length=500)),
                ('progress_percent', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('result_data', models.JSONField(blank=True, help_text='Task result data (on success)', null=True)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message (on failure)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Task completion time', null=True)),
                ('company', models.ForeignKey(help_text='Company being processed', on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to='csi300.csi300company')),
            ],
            options={
                'verbose_name': 'Generation Task',
                'verbose_name_plural': 'Generation Tasks',
                'db_table': 'csi300_generation_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='csi300_gene_status_fa9fc0_idx')],
            },
        ),
    ]
