# Generated by Django 4.2.7 on 2025-06-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FredIndicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('series_id', models.CharField(max_length=50)),
                ('indicator_name', models.CharField(max_length=200)),
                ('indicator_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('source', models.CharField(default='FRED', max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fred_indicators',
                'ordering': ['-date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FredSeriesInfo',
            fields=[
                ('series_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('seasonal_adjustment', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fred_series_info',
                'managed': False,
            },
        ),
    ]
